---
- name: Setup Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: mount
    - role: docker
    - role: node_exporter
    - role: cadvisor
    - role: statsd_exporter
    - role: filebeat
    - role: clamav
    - role: gpg_config
    - role: aide
    - role: additional_process_hardening
    - role: warning_banners
    - role: auditd
    - role: sshd_hardening
    - role: pam
    - role: user_ssh_certificate
    - role: earlyoom_memory_limits

  tasks:
    - name: Include devbox role if is_devbox is true (i.e., devbox should run only if bench does not)
      include_role:
        name: devbox
      when: is_devbox_server | default(false)

    - name: Include bench role if is_devbox is false 
      include_role:
        name: bench
      when: not (is_devbox_server | default(false))
